require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '11.0'

target 'MyShoppingListApp' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true

  # pod 'simdjson', path: '../node_modules/@nozbe/simdjson'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'MyShoppingListAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })

  # pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true

  post_install do |installer|
    react_native_post_install(installer)
  end
end